swagger: "2.0"
info:
  title: Swagger Ruang Opini
  description: Serverless APIs with API Gateway
  version: 1.0.0
tags:
- name: policies
  description: Everything about policies
schemes:
- https
- http
produces:
- application/json
paths:
  /AllPolicyCategories:
    get:
      tags:
      - policies
      operationId: getAllPolicyCategory
      description: Returns all policy categories
      x-google-backend:
        address:  # Replace with Cloud Function trigger URL to get all policy category
        protocol: h2
      responses:
        '200':
          description: successful operation
        '404':
          description: Data is not found
  /PolicyByType:
    get:
      tags:
      - policies
      operationId: getPolicyByType
      description: Returns all policy by type
      x-google-backend:
        address: # Replace with Cloud Function trigger URL to get policy by type
        protocol: h2
      responses:
        '200':
          description: successful operation
        '404':
          description: Data is not found
  /PolicyByCategory:
    get:
      tags:
      - policies
      operationId: getPolicyByCategory
      description: Returns all policy by category
      x-google-backend:
        address: # Replace with Cloud Function trigger URL to get policy by category
        protocol: h2
      responses:
        '200':
          description: successful operation
        '404':
          description: Data is not found
  /DocumentPolicy:
    get:
      tags:
      - policies
      operationId: getDocumentPolicy
      description: Returns document policy
      x-google-backend:
        address: # Replace with Cloud Function trigger URL to get document policies
        protocol: h2
      responses:
        '200':
          description: successful operation
        '404':
          description: Data is not found