swagger: "2.0"
info:
  title: Sentiment Analysis
  description: Serverless APIs with API Gateway
  version: 1.0.0
schemes:
- https
- http
produces:
- application/json
paths:
  /Trending:
    get:
      operationId: getPolicyTrending
      description: Returns trendings related to policy
      x-google-backend:
        address: # Replace with Cloud Function trigger URL to get all policy trending
        protocol: h2
      responses:
        '200':
          description: successful operation
        '404':
          description: Data is not found
  /Responses:
    get:
      operationId: getUserResponse
      description: Returns percentage of user response by trending
      x-google-backend:
        address: # Replace with Cloud Function trigger URL to get tweet sentiment result by trending
        protocol: h2
      responses:
        '200':
          description: successful operation
        '404':
          description: Data is not found
  /Buzzer:
    get:
      operationId: getBuzzer
      description: Returns buzzers percentage by trending
      x-google-backend:
        address: # Replace with Cloud Function trigger URL to get buzzer detection result by trending
        protocol: h2
      responses:
        '200':
          description: successful operation
        '404':
          description: Data is not found